<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>LDI12.Engine</RootNamespace>
    <AssemblyName>LDI12.Engine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LDI12.Core\LDI12.Core.csproj" />
  </ItemGroup>

</Project>
