<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>LDI12.Reports</RootNamespace>
    <AssemblyName>LDI12.Reports</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LDI12.Core\LDI12.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
